---
- name: Install packages
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - wget
      - rsync
      - gcc
      - libstdc++.i686
      - nc
      - tar
      - unzip
- name: Install steamcmd
  unarchive:
      src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes
- name: Install 7dtd server
  expect:
    command: /usr/local/bin/steamcmd.sh
    timeout: null
    responses:
      "Steam>":
        - "login anonymous"
        - "force_install_dir /root/7dtd"
        - "app_update 294420 validate"
        - "exit"
