---
- name: Install steamcmd
  unarchive:
      src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes
- name: Install palworld server
  expect:
    command: /usr/local/bin/steamcmd.sh
    timeout: null
    responses:
      "Steam>":
        - "login anonymous"
        - "force_install_dir /home/game-user/palworld_server"
        - "app_update 2394010 validate"
        - "exit"
  notify: Restart palworld_server
- name: Copy /etc/systemd/system/palworld_server.service
  template:
    src: templates/etc/systemd/system/palworld_server.service
    dest: /etc/systemd/system/palworld_server.service
  notify: Restart palworld_server
- name: Change owner and group of /home/game-user/palworld_server
  file:
    path: /home/game-user/palworld_server
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true
    mode: 0755
- name: Reload systemd unit files
  systemd:
    daemon-reload: yes
- name: Enabled palworld_server
  systemd:
    name: palworld_server
    enabled: yes
  notify: Restart palworld_server
