---
- name: Mkdir /root/.bin
  file:
    path: /root/.bin
    owner: root
    group: root
    mode: 0755
    state: directory
- name: Template /root/.bin/ebs_mount.sh
  template:
    src: templates/root/.bin/ebs_mount.sh
    dest: /root/.bin/ebs_mount.sh
    mode: 0755
- name: Copy /etc/systemd/system/ebs_mount.service
  file:
    src: files/etc/systemd/system/ebs_mount.service
    dest: /etc/systemd/system/ebs_mount.service
  notify: Restart ebs_mount
- name: Reload systemd unit files
  systemd:
    daemon-reload: yes
- name: Enabled ebs_mount.service
  systemd:
    name: ebs_mount
    enabled: yes
  notify: Restart ebs_mount
