# MUST: run after ebs task
- name: Install steamcmd
  unarchive:
      src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes
- name: Install 7dtd server
  remote_user: "{{ user }}"
  expect:
    command: /usr/local/bin/steamcmd.sh
    timeout: null
    responses:
      "Steam>":
        - "login anonymous"
        - "force_install_dir /ebs/7dtd_server"
        - "app_update 294420 validate"
        - "exit"
