# MUST: run after ebs task
- name: Install steamcmd
  unarchive:
      src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: /usr/local/bin
      remote_src: yes
- name: Install 7dtd server
  expect:
    command: /usr/local/bin/steamcmd.sh
    timeout: null
    responses:
      "Steam>":
        - "login anonymous"
        - "force_install_dir /ebs/7dtd_server"
        - "app_update 294420 validate"
        - "exit"
- name: Change owner and group of /ebs/7dtd_server
  file:
    path: /ebs/7dtd_server
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true
    mode: 0755
