---
- name: Install packages
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - wget
      - rsync
      - gcc
      - libstdc++.i686
      - nc
      - tar
      - unzip
