- name: Add group "{{ group }}"
  group:
    name: "{{ group }}"
    gid: 500
    state: present
- name: Add user "{{ user }}"
  user:
    name: "{{ user }}"
    uid: 501
    group: "{{ group }}"
    comment: "voyagemarketing's service app user"
    home: "/home/{{ user }}"
    shell: /bin/bash
